/* Seasonal knowledge for Brisbane, from Nathan's own "Bonsai Monthly Maintenance Calendar" spreadsheet
   and the Red Dragon Bonsai (Currumbin) newsletters 2007–2014. s = source. */
const YC = 'Your monthly calendar';
export const TIPS = {
 1:[{t:'Feeding',x:'Ease off feeding most trees in hot, dry spells. They go into summer dormancy and extra nitrogen just burns the new growth. Pines and junipers are the exception.',s:YC+' · Red Dragon Jan 2009'},
    {t:'Wire',x:'Check wire after heavy rain. Branches swell fast; maples, azaleas and camellias can scar within 3–4 weeks. Wrapping with soaked raffia first gives protection.',s:'Red Dragon Jan 2008, Jan 2012'},
    {t:'Watering',x:'After long rain keep watering for a week or so. Potted trees stay in high-uptake mode and dry out quickly once the sun returns. Tilt pines, junipers and figs at one end to drain.',s:'Red Dragon Jan & Feb 2008, Jan 2012'},
    {t:'Black pines',x:'Water and mist black pines every day through summer.',s:YC},
    {t:'Sun',x:'Use 30–50% shade cloth over the hottest months, not the shade of a tree.',s:'Red Dragon Jan 2008'}],
 2:[{t:'Feeding',x:'Heavy rain leaches fertiliser out of the pot. Re-feed once it settles.',s:'Red Dragon Nov 2008, Dec 2010'},
    {t:'Junipers',x:'Keep foliage pads thin so light reaches the inside. Pinch new growth; never cut through needles or the tips go brown.',s:'Red Dragon Feb 2008'},
    {t:'Light pruning',x:'Keep cutting back new shoots and focus growth where you need it.',s:YC}],
 3:[{t:'Feeding',x:'Start feeding again. Trees store nutrients through autumn for spring growth, and this is where most people skimp.',s:YC+' · Red Dragon Mar 2009, Mar 2012'},
    {t:'Liquid potash',x:'Every 2 weeks for flowering and fruiting trees (bougainvillea, azalea, jaboticaba) until the buds are just about to open.',s:YC+' · Red Dragon Mar 2008, Apr 2010'},
    {t:'Azaleas',x:'Stop trimming azaleas. Next spring\'s flower buds have formed.',s:YC+' · Red Dragon Mar 2008'},
    {t:'Wire',x:'Trunks thicken in autumn as trees store food. Check wire, and re-check anything wired now in a month.',s:'Red Dragon Mar 2008, Mar 2009'},
    {t:'Cleaning',x:'Clean old needles out of junipers with a chopstick, and start the major clean-up on black pines.',s:YC+' · Red Dragon Mar 2008'},
    {t:'Autumn repots',x:'Only trim roots lightly if you repot now. Leave black pines, azaleas and cedars until spring.',s:YC+' · Red Dragon Mar 2010, Mar 2012'}],
 4:[{t:'Feeding',x:'Keep feeding. Growth looks slow but the tree is storing for spring; skip it and small branchlets die back.',s:'Red Dragon Apr 2009'},
    {t:'Deciduous',x:'As leaves drop, cut back branches that have grown too long, upward or downward, and wire the rest into place.',s:'Red Dragon Apr 2009, Apr 2010'},
    {t:'Black pines',x:'Once this year\'s needles have hardened, pull last year\'s old needles to let air and light in.',s:YC}],
 5:[{t:'Feeding',x:'Last feed for the season, at half strength.',s:YC},
    {t:'Lime sulphur',x:'Spray monthly May–July at 10–15 mL per litre, late afternoon, benches too. Not on natives.',s:YC+' · Red Dragon May 2008, May 2009'},
    {t:'Hold off',x:'Don\'t cut back deciduous trees yet; sap is still moving into storage. Leave any remaining repots until spring.',s:'Red Dragon May 2009'},
    {t:'Pines',x:'Clean out old yellow and brown needles.',s:YC}],
 6:[{t:'Watering',x:'Let trees nearly dry out between waterings. Cooler roots take up far less.',s:YC+' · Red Dragon Jun 2009'},
    {t:'Wiring',x:'Good time to wire while you can see the structure. Wire when the tree is on the dry side; freshly watered branches snap like fresh celery.',s:YC+' · Red Dragon Jun 2009'},
    {t:'Elms',x:'Cut elms back hard (be ruthless with the branchlets) for fine winter twigging.',s:'Red Dragon Jun 2009, Jun 2011'},
    {t:'Repotting',x:'Deciduous repots can start in Queensland.',s:YC+' · Red Dragon Jun 2010'},
    {t:'Buying',x:'Good time to buy stock before nurseries pot it up and prices rise.',s:YC}],
 7:[{t:'Repotting',x:'Repot elms, junipers and black pines. Remove about a third of the root ball (the thick roots), keep the fine ones, chopstick out air pockets, add slow-release, soak it in, then 7–10 days somewhere warm and sheltered.',s:YC+' · Red Dragon Jul 2008, Jul 2009'},
    {t:'Pruning',x:'Hard prune elms before leaf bud, back to 2 buds on each branchlet. Black pines too.',s:YC+' · Red Dragon Jul 2008, Jul 2011'},
    {t:'Wiring',x:'Good month to wire black pines.',s:YC},
    {t:'Roots',x:'Roots stop growing when nights drop below about 12°C; go by night temperatures, not the calendar.',s:'Red Dragon Jul 2009'}],
 8:[{t:'Repotting',x:'Pines this month. Swamp cypress as the new buds extend.',s:YC+' · Red Dragon Aug 2008'},
    {t:'Swamp cypress',x:'Hard prune in late winter; it buds back prolifically. Remove wire quickly, it marks easily.',s:'Red Dragon Aug 2008'},
    {t:'Liquid potash',x:'Continue until flower buds are just about to open, then stop.',s:YC}],
 9:[{t:'Repotting',x:'Black pines, azaleas, cedars and swamp cypress.',s:YC},
    {t:'Feeding',x:'Fortnightly for junipers and broadleaf trees. Black pines: low-nitrogen only while candles are extending fast.',s:YC+' · Red Dragon Sep 2008'},
    {t:'Decandling',x:'Remove dominant or overextended black pine candles to balance strength.',s:YC},
    {t:'Watering',x:'Daily for junipers and broadleaf trees; black pines only every 3 days during strong candle growth.',s:YC},
    {t:'Junipers',x:'Pinch new growth at about 20 mm and keep pads around 25 mm thick. Let junipers nearly dry between waterings.',s:'Red Dragon Sep 2008'}],
 10:[{t:'Repotting',x:'Elms and junipers can still be done with careful aftercare. Figs prefer now or later in the season.',s:YC+' · Red Dragon Oct 2007'},
    {t:'Pests',x:'Spray preventively. Tap a branch over white paper to spot red spider mite; watch junipers for white louse scale; a loose, sickly tree may have curl grubs in the roots.',s:'Red Dragon Oct 2007, Oct 2008'},
    {t:'Turn your trees',x:'Turn every 2–3 weeks so both sides grow evenly.',s:YC+' · Red Dragon Dec 2007'},
    {t:'Pruning',x:'Cut back new shoots to the 2nd leaf for smaller leaves and better ramification.',s:YC}],
 11:[{t:'Repotting',x:'Figs.',s:YC},
    {t:'Black pines',x:'Feed black pines to regain vigour after candle work.',s:YC},
    {t:'Heat',x:'Liquid seaweed with the feed helps trees through heat stress. Shade pots on hot, windy days.',s:'Red Dragon Nov 2009 · '+YC},
    {t:'Wire',x:'Growth is vigorous – watch for wire biting in.',s:YC}],
 12:[{t:'Defoliating',x:'December only, broadleaf trees such as figs. Healthy trees only; cut the leaf stalk just above the joint, take the growing tip too, keep in full sun and water less until new leaves form.',s:YC+' · Red Dragon Nov 2008, Dec 2010, Nov 2011'},
    {t:'Black pines',x:'Trim back to 2–4 needles on the branchlets. Water and mist daily.',s:YC},
    {t:'Watering',x:'Hot days may need two waterings, or a mist in the heat of the day.',s:'Red Dragon Dec 2007'},
    {t:'Feeding',x:'Ease off during hot spells (pines and junipers excepted).',s:YC}]
};
/* species notes shown on each tree's Calendar tab */
export const NOTES = {
 pine:['Repot July–September; never in autumn.','Decandle in September; trim to 2–4 needles in December; clean old needles March–June.','Low-nitrogen feed while candles grow; feed in November to regain vigour.','Diatomite in the mix suits black pines: they like water but not wet feet.','Black pines don\'t bud back on old wood, so don\'t rely on sacrifice branches to thicken branches.'],
 elm:['Repot June–October.','Prune hard in June–July before leaf bud, back to 2 buds.','Wire in winter while leafless; check it in spring.','Elms and junipers were the worst hit by spider mite and scale in humid summers.'],
 juniper:['Repot July–October.','Pinch, never cut through needles. Pads about 25 mm thick.','Clean out dead needles with a chopstick in March and September.','Let them nearly dry between waterings. Watch for red spider mite and white louse scale.'],
 fig:['Repot October–November; figs tolerate repotting most of the year with 2 weeks of shade and misting.','Defoliate in December, then full sun and less water.','Diatomite in the mix suits figs.'],
 swamp:['Repot each spring as buds extend (August–September).','Keep moist at all times but don\'t stand it in water.','Feed every 1–2 weeks in the growing season; very vigorous.','Hard prune in late winter. Pinch new shoots through the season.','Remove wire promptly; it marks easily. Guy wires work well.'],
 azalea:['No trimming after March: flower buds have formed.','Liquid potash every 2 weeks from March until buds are about to open.','Repot September–October.'],
 bougie:['Liquid potash every 2 weeks from March until buds are about to open.','Repot in warm weather (October–December).'],
 african:['Fruiting tree: liquid potash every 2 weeks from March until flower buds are about to open.','Subtropical. Repot in spring (September–November).'],
 mela:['Australian native: skip it when spraying lime sulphur.'],
 cler:['Broadleaf: fortnightly feed in the growing season.','Struggled in a fully inorganic mix; current mix includes pine bark.'],
 podo:['Repot September–October.']
};
/* collection-wide reminders that open in a given month */
export const COLLECTION = {3:['Restart feeding (autumn storage)','Liquid potash for flowering & fruiting trees, every 2 weeks'],5:['Last feed of the season, half strength','Lime sulphur spray (monthly to July, not natives)'],9:['Fortnightly feeding for junipers & broadleaf'],12:['Ease off feeding in hot spells'],10:['Turn all trees every 2–3 weeks']};
